count: 1000
filetype: "png"
assets:
  path: "assets"
  layers:
    - name: "background"
      required: True
    - name: "punks"
      required: True
      rarity_weights:
        alien: .1
        ape: .9
        female1: 12
        female2: 12
        female3: 12
        female4: 12
        male1: 12
        male2: 12
        male3: 12
        male4: 12
        zombie: 3
    - name: "top"
      required: True
    - name: "beard"
      required: True
    - name: "glasses"
      required: False
    - name: "mouth"
      required: False
    - name: "cheek"
      required: False
    - name: "chain"
      required: False
      rarity_weights:
        None: 80
        gold_chain: 10
        silver_chain: 10

rules:
  - filter: "notequals"
    trait_1:
      name: "punks"
      value: "alien"
    trait_2:
      name: "top"
      value: "wild_blonde"
  - filter: "notequals"
    trait_1:
      name: "punks"
      value: "alien"
    trait_2:
      name: "top"
      value: "wild_hair"
  - filter: "equals"
    trait_1:
      name: "background"
      value: "purple"    
    trait_2:
      name: "punks"
      value: "female1"